apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tektutor-ingress
  labels:
     app: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ngnix.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
      - host: devops.tektutor.org 
        http:
          paths:
          - path: /login
            backend:
               serviceName: login
               servicePort: 80 
          - path: /nginx
            backend:
               serviceName: nginx
               servicePort: 80
