apiVersion: v1
kind: ReplicationController
metadata:
  name: hello 
spec:
  replicas: 3
  selector:
    app: hello 
  template:
    metadata:
      name: hello 
      labels:
        app: hello 
    spec:
      containers:
      - name: hello 
        image: tektutor/hello-ms:2.0
        ports:
        - containerPort: 80
